### ISSUE TITLE
Add data use terms to datasets

### ISSUE THREAD

**Issue by jopasserat** [AcademicTorrents/academictorrents.com-feedback#1]
Some fields share datasets that cannot be completely open data for ethics reason. Typical example are medical datasets with patient information (even anonymised).

The associated sharing platforms often have the end user sign a data use term that once validated garnts the user full access to the dataset.

You can see one of these data use terms here:
http://humanconnectome.org/data/data-use-terms/open-access.html

It might be helpful to allow sharers to post these data use terms along with their data sets.
I'm not sure whether including a text file mentioning the use terms in the torrent is sufficient from a legal point of view.

One other option would be to add a validation box on the download page.

Option 1 makes more sense for torrents as the dataset might then be shared to users who did not sign the data use terms from one of the online platforms.

I guess a very cool feature would be to highlight the data use terms in a field below the licence.

**Comment by ieee8023** [comment]
How about this? Try to download this dataset.

http://academictorrents.com/details/83a4dd7e764dfd34bca103be8b6094a9bd346d30

**Comment by jopasserat** [comment]
That looks great!

I guess you'll add a new text box on the upload page? With a checkbox "mandatory" maybe?

**Comment by ieee8023** [comment]
We are close to a upload page overhaul. I can add one in the meantime. We can have it so if you leave it blank it will not ask the user to accept terms.

**Comment by ieee8023** [comment]
@jopasserat Check out the updated upload page.
