### ISSUE TITLE
Processing Error 400 when trying to upload a torrent

### ISSUE THREAD

**Issue by sergiuoprea** [AcademicTorrents/academictorrents.com-feedback#13]
Hi there,

I am trying to upload a torrent created with transmission client. I am getting the following error during the process:
`Error (400, Processing Error): {"msg","Missing form data: descr"}`

All the form fields were filled and the torrent was successfully validated. What I am doing wrong? I don't know if this is a problem related to a field from the uploading form.

Thanks in advance for the support.

**Comment by ieee8023** [comment]
What web browser are you using?

**Comment by sergiuoprea** [comment]
Google Chrome. I've just tried with Microsoft Edge web browser and same error.

**Comment by ieee8023** [comment]
I think I found the bug. When the bibtex entry was in a unparsable state it would prevent you from editing it. This was compounded by the bibtex being an empty string so it would cause an error on the server.
I added more defensive code. See how it works now.
