### ISSUE TITLE
Use standard license identifiers

### ISSUE THREAD

**Issue by nemobis** [AcademicTorrents/academictorrents.com-feedback#14]
The upload form states:

> If you have a license please enter a license in the Bibtex (e.g. GPL, CC, CC-SA).

Do you have concerns about adopting standard identifiers like URLs or short SPDX names? https://spdx.org/licenses/

**Comment by ieee8023** [comment]
Yes, that sounds fine. This field is for you to convey to the user what the license is. It should be as clear as possible.
