### ISSUE TITLE
Can't Update / Populate conditional fields of torrent created from REST API

### ISSUE THREAD

**Issue by jopasserat** [AcademicTorrents/academictorrents.com-feedback#2]
It seems impossible to edit the fields hidden behind a checkbox when the torrent was created from the API.

![screenshot from 2017-04-05 14-52-06](https://cloud.githubusercontent.com/assets/472083/24708711/9f451ea4-1a0f-11e7-95b5-e3d85289cbc8.png)

Problem could be reproduced on both Chromium and Firefox and two different machine.

The API was used through the [torrent uploader python app](https://github.com/AcademicTorrents/academictorrents_uploader).

**Comment by ieee8023** [comment]
Sorry for delay! We are looking into this!

**Comment by ieee8023** [comment]
This issue was caused because the bibtex field was not properly formatted. The API does not prevent this. We added an error and instructions on how to fix the issue when you go to edit a torrent that does not have a properly formatted bibtex field.
