### ISSUE TITLE
how can i add edx courses to your site and some 

### ISSUE THREAD

**Issue by yassine1991** [academictorrents/academictorrents.com-feedback#21]
hi,
i just want to add some edx courses to your site and i am wondering how can i do that and thanks for the great content because some i wipe my pc but when i look for them online i can't find them and thank you

**Comment by ieee8023** [comment]
Please email us to discuss this.

**Comment by yassine1991** [comment]
Hi,
Thank you for your responce i just loked for the courses introduction to
networking and i did't find it so i want to store my dowloads courses i
want to know if academic torrent can do that
