### ISSUE TITLE
.torrent file had incorrect file contents, but magnet link had correct contents

### ISSUE THREAD

**Issue by tenkabuto** [AcademicTorrents/academictorrents.com-feedback#3]
Hi, I just wanted to report that the .torrent for [this course](http://academictorrents.com/details/e2c129491a3841bfac5d7b08b41ad79387132a23) contains the wrong contents, but the magnet link has the correct contents. I don't know why this might be.

**Comment by ieee8023** [comment]
Thanks for reporting this. It is fixed now. We will look into why this happened.
