### ISSUE TITLE
Email send option for verification/reset is broken.

### ISSUE THREAD

**Issue by Alpha-Scorpii** [AcademicTorrents/academictorrents.com-feedback#8]
tried multiple time sending email for password rest or signup confirmation is broken.Not receiving any mail even after success message.

**Comment by ieee8023** [comment]
The mail is working but some providers (hotmail and outlook) block emails from us and will not respond to our appeals. Please contact the group running your mail service and ask them to allow emails from us.

**Comment by Alpha-Scorpii** [comment]
By the way, may I know from which sender I will be receiving email on success?

**Comment by ieee8023** [comment]
The from email is: noreply@academictorrents.com
